---
title: "class-19-11-2019"
author: "Aysha Emmerson"
date: "19/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(skimr)
library(fs)

download.file("https://github.com/TheUpshot/2018-live-poll-results/archive/master.zip", destfile = "master.zip")

unzip("master.zip")

raw <- read_csv("2018-live-poll-results-master/data/elections-poll-az02-1.csv", 
                col_types = cols(.default = col_character(),
                                 turnout_scale = col_double(),
                                 turnout_score = col_double(),
                                 w_LV = col_double(),
                                 w_RV = col_double(),
                                 final_weight = col_double(),
                                 timestamp = col_datetime(format = "")))
                

my_list <- dir_ls("2018-live-poll-results-master/data/")
  
raw <- map_dfr(my_list, .id = "source", read_csv, col_types = cols(.default = col_character(),
                                 turnout_scale = col_double(),
                                 turnout_score = col_double(),
                                 w_LV = col_double(),
                                 w_RV = col_double(),
                                 final_weight = col_double(),
                                 timestamp = col_datetime(format = "")))

# first variable source which gives you each individual file 

```


```{r}

# Create a 0/1 variable dvote for democratic vote 
# Create a 0/1 variable female

skim(raw)

glimpse(raw)

# Relationships with dvote and female 

x <- raw %>%
  mutate(dvote = ifelse(response == "Dem", 1, 0)) %>%
  mutate(female = ifelse(gender == "Female", 1, 0)) %>%
  select(dvote, female) %>%

file.delete("master.zip", "2018-live-poll-results-master/")
  
  # Logistic regression
  # what does 0.42 mean
  # Women more likely then men to vote dem
  # HOW CAN I use the model with new data?
  
my_data <- tibble(female = c(0,0,1))

glm_obj <- glm(dvote ~ female, data = x, family = "binomial")

predict(glm_obj, newdata = my_data, type = c("response"))

# how to interpret 0.4?
# probability that you vote dem if you are male
# furst two numbers are the same therefore both male
# How does number above (predicted values for new data) connect to the coefficient intercept
# female 0.1042 is that amount more likely to vote dem
# predict new data with new data 
# if you are not female 40% chance of voting dem 
# three numbers appear. 
# add a prediction column to x

x %>%
  mutate(prediction = predict(glm_obj, type = c("response")))

# How to figure out which model is the best thing?
# model fails totally with model one 

x %>%
  group_by(dvote) %>%
  summarise(avg = mean(prediction))

# same vlaue for prediction for dem and non dem 
# most of time predicting low numbers
# not a good model as numbers diverge 


```

